version: "3.9"

networks:
  production:

services:
  postgres:
    container_name: retold-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "DB_NAME"
      POSTGRES_USER: "DB_USER"
      POSTGRES_PASSWORD: "DB_PASS"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - production

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/path-to-ssl'
      - '/path-to-ssl-key'
    depends_on:
      - backend
      - frontend
    networks:
      - production

  backend: 
    build:
      context: ./retold_server
    depends_on:
      - postgres
    networks:
      - production

  frontend: 
    build:
      context: ./retold_client/retold_client
    networks:
      - production
  
  bot:
    build:
      context: ./retold_bot
    depends_on:
      - postgres
    networks:
      - production

volumes:
  postgres-data: